/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.SIGUEA.GUI;

import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import net.datafaker.Faker;

/**
 *
 * @author Computer22
 */
public class asistencia extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(asistencia.class.getName());
    private DefaultTableModel modeloAsistencia;

    /**
     * Creates new form asistencia
     */
    public asistencia() {
        initComponents();

        configurarTablaJTregAsis();
        simularDatosConDataFaker();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTregAsis = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(16, 79, 139));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 20, 12, 20));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("IESTP Chincha");
        jLabel1.setToolTipText("");
        jPanel2.add(jLabel1);

        jLabel2.setForeground(new java.awt.Color(147, 197, 253));
        jLabel2.setText("Sistema de Asistencia");
        jPanel2.add(jLabel2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jPanel2, gridBagConstraints);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jPanel3, gridBagConstraints);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 20, 12, 20));
        jPanel4.setMinimumSize(new java.awt.Dimension(450, 57));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 5));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bienvenido, ");
        jPanel4.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Administrador");
        jPanel4.add(jLabel4);

        jButton1.setBackground(new java.awt.Color(66, 107, 154));
        jButton1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Inicio");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(127, 168, 213), 1, true));
        jButton1.setContentAreaFilled(false);
        jButton1.setMargin(new java.awt.Insets(6, 14, 6, 14));
        jButton1.setMaximumSize(new java.awt.Dimension(52, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(52, 23));
        jButton1.setPreferredSize(new java.awt.Dimension(90, 32));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel4.add(jButton1);

        jButton2.setBackground(new java.awt.Color(225, 29, 72));
        jButton2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cerrar Sesión");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        jPanel4.add(jButton2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jPanel4, gridBagConstraints);

        JTregAsis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "N°", "Código", "Apellidos y Nombres", "DNI", "Asistencia (P / A / T)"
            }
        ));
        jScrollPane1.setViewportView(JTregAsis);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    ///Empieza rellena los datos
    public void simularDatosConDataFaker() {
        if (modeloAsistencia == null) {
            configurarTablaJTregAsis();
        }

        modeloAsistencia.setRowCount(0);
        Faker faker = new Faker(new Locale("es"));

        for (int i = 1; i <= 10; i++) {
            String num = String.valueOf(i);
            String codigo = "2026" + String.format("%04d", i);
            String apellidosNombres = faker.name().lastName()
                    + " " + faker.name().lastName()
                    + ", " + faker.name().firstName();
            String dni = faker.number().digits(8);
            String asistencia = "P";

            Object[] fila = {num, codigo, apellidosNombres, dni, asistencia};
            modeloAsistencia.addRow(fila);
        }
    }

    ///finaliza el relleno de datos
    
    
    public void configurarTablaJTregAsis() {
        String[] columnas = {"N°", "Código", "Apellidos y Nombres", "DNI", "Asistencia (P / A / T)"};

        // 1. Crear el modelo de datos
        modeloAsistencia = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                // Hacemos editable ÚNICAMENTE la columna de asistencia (índice 4)
                return column == 4;
            }
        };

        JTregAsis.setModel(modeloAsistencia);

        // 2. CONFIGURAR LOS ANCHOS DE LAS COLUMNAS (Para evitar el texto cortado)
        JTregAsis.getColumnModel().getColumn(0).setPreferredWidth(40);  // N°
        JTregAsis.getColumnModel().getColumn(1).setPreferredWidth(100); // Código
        JTregAsis.getColumnModel().getColumn(2).setPreferredWidth(280); // Apellidos y Nombres (Más ancho)
        JTregAsis.getColumnModel().getColumn(3).setPreferredWidth(90);  // DNI
        JTregAsis.getColumnModel().getColumn(4).setPreferredWidth(160); // Asistencia (Espacio para los botones)

        // Ajustar la altura de las filas para que quepan cómodamente los botones
        JTregAsis.setRowHeight(30);

        // 3. ASIGNAR LOS COMPONENTES DE BOTONES A LA COLUMNA 4
        AsistenciaRendererEditor renderEditor = new AsistenciaRendererEditor();
        JTregAsis.getColumnModel().getColumn(4).setCellRenderer(renderEditor);
        JTregAsis.getColumnModel().getColumn(4).setCellEditor(renderEditor);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new asistencia().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTregAsis;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables


}
