/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.SIGUEA.GUI;

import java.awt.Color;
import java.net.URL;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.SwingConstants;

/**
 *
 * @author UPSJB
 */
public class DashboardFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardFrame.class.getName());

    /**
     * Creates new form DashboardFrame
     */
    public DashboardFrame() {
        initComponents();
        configurarBoton(btnAsistencia, "asistencia.png",
                "Tomar Asistencia",
                "Registrar asistencia de alumnos por curso y fecha"
        );

        configurarBoton(btnListarAlumnos, "alumnos.png",
                "Listar Alumnos",
                "Ver y buscar el padrón de estudiantes matriculados"
        );

        configurarBoton(btnUsuarios, "usuarios.png",
                "Gestionar Usuarios",
                "Administrar cuentas y permisos del sistema"
        );

        configurarBoton(btnDocentes, "docentes.png",
                "Listar Docentes",
                "Consultar el listado de docentes activos"
        );

        configurarBoton(btnMaterias, "materias.png",
                "Listar Materias",
                "Ver cursos, horarios y asignaciones docentes"
        );

        configurarBoton(btnReportes, "reportes.png",
                "Reportes Generales",
                "Consultar estadísticas y generar reportes PDF"
        );

        configurarBoton(btnCrearAlumno, "crear_alumno.png",
                "Crear Alumno",
                "Registrar un nuevo estudiante en el sistema"
        );

        configurarBoton(btnCrearUsuario, "crear_usuario.png",
                "Crear Usuario",
                "Agregar nuevo usuario administrador o docente"
        );
    }

    private void configurarBoton(JButton boton, String imagen, String titulo, String descripcion) {
        // 1. Intenta cargar desde "/images/" o cambia a "/imges/" si esa era tu carpeta original
        URL url = getClass().getResource("/images/" + imagen);

        if (url != null) {
            // Redimensionar nativamente con alta calidad (Proporción perfecta 40x49)
            ImageIcon iconoOriginal = new ImageIcon(url);
            java.awt.Image imgEscalada = iconoOriginal.getImage().getScaledInstance(40, 49, java.awt.Image.SCALE_SMOOTH);
            boton.setIcon(new ImageIcon(imgEscalada));
        } else {
            System.out.println("No se encontró la imagen: " + imagen + ". Verifica si tu carpeta es /images/ o /imges/");
        }

        // 2. Aplicar diseño web (Fondo Blanco Limpio y Borde)
        boton.setBackground(Color.WHITE);
        boton.setOpaque(true);
        boton.setContentAreaFilled(true);
        boton.setFocusPainted(false);
        boton.setBorder(BorderFactory.createLineBorder(new Color(226, 232, 240), 1));

        // 3. HTML Limpio SOLO para el texto (Sin la etiqueta <img> que rompe el código)
        boton.setText(
                "<html>"
                + "<center>"
                + "<font size='4' color='#1E293B'><b>" + titulo + "</b></font>"
                + "<br><br>"
                + "<font size='2' color='#64748B'>" + descripcion + "</font>"
                + "</center>"
                + "</html>"
        );

        // 4. Forzar que el Icono se posicione ARRIBA del texto
        boton.setVerticalTextPosition(SwingConstants.BOTTOM);
        boton.setHorizontalTextPosition(SwingConstants.CENTER);
        boton.setIconTextGap(15); // Espacio de separación entre el círculo y el texto
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAsistencia = new javax.swing.JButton();
        btnListarAlumnos = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnDocentes = new javax.swing.JButton();
        btnMaterias = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnCrearAlumno = new javax.swing.JButton();
        btnCrearUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setBackground(new java.awt.Color(255, 51, 51));
        setPreferredSize(new java.awt.Dimension(1040, 510));

        jPanel1.setBackground(new java.awt.Color(16, 79, 139));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 20, 12, 20));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("IESTP Chincha");
        jLabel1.setToolTipText("");
        jPanel2.add(jLabel1);

        jLabel2.setForeground(new java.awt.Color(147, 197, 253));
        jLabel2.setText("Sistema de Asistencia");
        jPanel2.add(jLabel2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jPanel2, gridBagConstraints);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jPanel3, gridBagConstraints);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 20, 12, 20));
        jPanel4.setMinimumSize(new java.awt.Dimension(450, 57));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 5));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bienvenido, ");
        jPanel4.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Administrador");
        jPanel4.add(jLabel4);

        jButton1.setBackground(new java.awt.Color(66, 107, 154));
        jButton1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Inicio");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(127, 168, 213), 1, true));
        jButton1.setContentAreaFilled(false);
        jButton1.setMargin(new java.awt.Insets(6, 14, 6, 14));
        jButton1.setMaximumSize(new java.awt.Dimension(52, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(52, 23));
        jButton1.setPreferredSize(new java.awt.Dimension(90, 32));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel4.add(jButton1);

        jButton2.setBackground(new java.awt.Color(225, 29, 72));
        jButton2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cerrar Sesión");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        jPanel4.add(jButton2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jPanel4, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 6, 1, 1, new java.awt.Color(59, 130, 246)));
        jPanel6.setMinimumSize(new java.awt.Dimension(981, 34));
        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(981, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Módulos disponibles —");

        jLabel6.setText("Seleccione una opción para continuar.");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(663, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAsistencia.setText("<html>\n<center> <img src=\"file:app/src/main/resources/imges/asistencia.png\" width=\"40\" height=\"40\"> <br><br>\n    <font size=\"4\"><b>Listar Alumnos</b></font> <br><br>\n    <font size=\"2\" color=\"#64748B\">Ver y buscar el padrón de estudiantes matriculados</font>\n</center>\n\n</html>");
        btnAsistencia.setActionCommand("<html>\n<center>\n\n<font size=\"4\"><b>Tomar Asitencia</b></font>\n<br><br>\n<font size=\"2\" color=\"#64748B\">Registrar asistencia de alumnos por curso y fecha</font>\n</center>\n</html>");
        btnAsistencia.setOpaque(true);
        btnAsistencia.setPreferredSize(new java.awt.Dimension(231, 142));
        btnAsistencia.addActionListener(this::btnAsistenciaActionPerformed);

        btnListarAlumnos.setText("<html>\n<center>\n  <img src=\"file:app/src/main/resources/imges/asistencia.png\" width=\"40\" height=\"40\">\n  <br><br>\n  <font size=\"4\"><b>Listar Alumnos</b></font>\n  <br><br>\n  <font size=\"2\" color=\"#64748B\">Ver y buscar el padrón de estudiantes matriculados</font>\n</center>\n</html>\n");
        btnListarAlumnos.setOpaque(true);
        btnListarAlumnos.setPreferredSize(new java.awt.Dimension(231, 142));

        btnUsuarios.setText("<html>\n<center>\n  <img src=\"file:app/src/main/resources/imges/asistencia.png\" width=\"40\" height=\"40\">\n  <br><br>\n  <font size=\"4\"><b>Gestionar Usuarios</b></font>\n  <br><br>\n  <font size=\"2\" color=\"#64748B\">Administrar cuentas y permisos del sistema</font>\n</center>\n</html>\n");
        btnUsuarios.setOpaque(true);
        btnUsuarios.setPreferredSize(new java.awt.Dimension(231, 142));

        btnDocentes.setText("<html>\n<center>\n  <img src=\"file:app/src/main/resources/imges/asistencia.png\" width=\"40\" height=\"40\">\n  <br><br>\n  <font size=\"4\"><b>Listar Docentes</b></font>\n  <br><br>\n  <font size=\"2\" color=\"#64748B\">Consultar el listado de docentes activos</font>\n</center>\n</html>\n");
        btnDocentes.setOpaque(true);
        btnDocentes.setPreferredSize(new java.awt.Dimension(231, 142));

        btnMaterias.setText("<html>\n<center>\n    <img src=\"file:app/src/main/resources/imges/asistencia.png\" width=\"40\" height=\"40\"> <br><br>\n    <font size=\"4\"><b>Listar Materias</b></font> <br><br>\n    <font size=\"2\" color=\"#64748B\">\n        Ver cursos, horarios y asignaciones docentes\n    </font>\n</center>\n\n</html>");
        btnMaterias.setOpaque(true);
        btnMaterias.setPreferredSize(new java.awt.Dimension(231, 142));

        btnReportes.setText("<html>\n<center>\n    <img src=\"file:app/src/main/resources/imges/asistencia.png\" width=\"40\" height=\"40\"> <br><br>\n    <font size=\"4\"><b>\n            Reportes Generales \n        </b></font> <br><br>\n    <font size=\"2\" color=\"#64748B\">\n        Consultar estadísticas y generar reportes PDF\n    </font>\n</center>\n\n</html>");
        btnReportes.setOpaque(true);
        btnReportes.setPreferredSize(new java.awt.Dimension(231, 142));

        btnCrearAlumno.setText("<html>\n<center>\n  <img src=\"file:app/src/main/resources/imges/asistencia.png\" width=\"40\" height=\"40\">\n  <br><br>\n  <font size=\"4\"><b>Crear Alumno</b></font>\n  <br><br>\n  <font size=\"2\" color=\"#64748B\">Registrar un nuevo estudiante en el sistema</font>\n</center>\n</html>\n");
        btnCrearAlumno.setOpaque(true);
        btnCrearAlumno.setPreferredSize(new java.awt.Dimension(231, 142));

        btnCrearUsuario.setText("<html>\n<center>\n  <img src=\"file:app/src/main/resources/imges/asistencia.png\" width=\"40\" height=\"40\">\n  <br><br>\n  <font size=\"4\"><b>Crear Usuario</b></font>\n  <br><br>\n  <font size=\"2\" color=\"#64748B\">Agregar nuevo usuario administrador o docente</font>\n</center>\n</html>\n");
        btnCrearUsuario.setOpaque(true);
        btnCrearUsuario.setPreferredSize(new java.awt.Dimension(231, 142));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(btnAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnListarAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnCrearAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListarAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCrearAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsistenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsistencia;
    private javax.swing.JButton btnCrearAlumno;
    private javax.swing.JButton btnCrearUsuario;
    private javax.swing.JButton btnDocentes;
    private javax.swing.JButton btnListarAlumnos;
    private javax.swing.JButton btnMaterias;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
